#!/usr/bin/env python3
"""Generate src/icons.css from the Phosphor icons actually used in the site.

Scans *.html and assets/js/*.js for `ph-<weight> ph-<name>` pairs, downloads any
missing SVGs (pinned @phosphor-icons/core, MIT licensed) into src/icons/, and
writes CSS that renders each icon as a currentColor mask. This replaces the
Phosphor icon-font loader, so pages load no third-party icon code or fonts.
"""
import glob, os, re, sys, urllib.parse, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORE = "https://cdn.jsdelivr.net/npm/@phosphor-icons/core@2.1.1/assets"
WEIGHTS = ("thin", "light", "regular", "bold", "fill", "duotone")

def used_pairs():
    pairs = set()
    files = glob.glob(os.path.join(ROOT, "*.html")) + glob.glob(os.path.join(ROOT, "assets/js/*.js"))
    for path in files:
        text = open(path, encoding="utf-8").read()
        for cls in re.findall(r"""(?:class=|className\s*=\s*|['"`])([^'"`<>]*\bph-(?:%s)\b[^'"`<>]*)""" % "|".join(WEIGHTS), text):
            toks = cls.split()
            weights = [t[3:] for t in toks if t[3:] in WEIGHTS and t.startswith("ph-")]
            names = [t[3:] for t in toks if t.startswith("ph-") and t[3:] not in WEIGHTS]
            for w in weights:
                for n in names:
                    pairs.add((w, n))
    return sorted(pairs)

def svg_for(weight, name):
    cache = os.path.join(ROOT, "src/icons", weight, name + ".svg")
    if not os.path.exists(cache):
        suffix = "" if weight == "regular" else "-" + weight
        url = f"{CORE}/{weight}/{name}{suffix}.svg"
        try:
            data = urllib.request.urlopen(url, timeout=20).read().decode()
        except Exception as e:
            sys.exit(f"icons.py: cannot fetch {url}: {e}")
        os.makedirs(os.path.dirname(cache), exist_ok=True)
        open(cache, "w").write(data)
    svg = open(cache).read()
    svg = re.sub(r"\s+", " ", svg).strip().replace('"', "'")
    return "data:image/svg+xml," + urllib.parse.quote(svg, safe=" =:/'.,-")

def main():
    pairs = used_pairs()
    out = [
        "/*! Phosphor Icons (https://phosphoricons.com), MIT License, Copyright (c) 2023 Phosphor Icons.",
        "   Generated by tools/icons.py - do not edit by hand. */",
        ".ph-thin,.ph-light,.ph-regular,.ph-bold,.ph-fill,.ph-duotone{display:inline-block;width:1em;height:1em;flex-shrink:0;"
        "vertical-align:-0.125em;font-style:normal;background-color:currentColor;"
        "-webkit-mask:var(--ph) center/contain no-repeat;mask:var(--ph) center/contain no-repeat}",
    ]
    for w, n in pairs:
        out.append(f'.ph-{w}.ph-{n}{{--ph:url("{svg_for(w, n)}")}}')
    open(os.path.join(ROOT, "src/icons.css"), "w").write("\n".join(out) + "\n")
    print(f"icons.py: {len(pairs)} icons -> src/icons.css")

if __name__ == "__main__":
    main()
